services:
  - docker

before_install:
  - docker pull apiaryio/emcc

scripts:
  - npm run build:docker

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master